### ISSUE TITLE
Simple chart with table fails with getAtribute error and retain colors defined in chart

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport-docx#13] opened 2020-07-21 18:26 UTC
I forked the example chart template and added data table to the chart and uploaded the docx file. Below is a link to the playground example

https://playground.jsreport.net/w/anon/0tW6ApHU

This fails with the following error

Error: Error while executing docx recipe. Cannot read property 'getAttribute' of undefined
    at module.exports (/app/node_modules/jsreport-core/lib/util/createError.js:11:13)
    at Reporter.createError (/app/lib/reporter.js:100:12)
    at /app/node_modules/jsreport-docx/lib/recipe.js:58:20
    at async executeRecipe (/app/lib/processor.js:130:5)
caused by: TypeError: Cannot read property 'getAttribute' of undefined
    at processChart (/app/node_modules/jsreport-docx/lib/postprocess/processChart.js:36:5)
    at /app/node_modules/jsreport-docx/lib/postprocess/drawingObject.js:71:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Are there specific limitations on styling the chart?

**Comment by bjrmatos** [comment] 2020-07-23 16:14
hi @iamanoopmk

can you describe the steps you follow in ms word to show the table directly in the chart?

basically, how did you change this

![Captura de pantalla 2020-07-23 a la(s) 11 13 24 a  m](https://user-images.githubusercontent.com/4262050/88310678-91890d80-ccd5-11ea-89b4-d1a9a762464a.png)

to this?

<img width="491" alt="Captura de pantalla 2020-07-23 a la(s) 11 13 51 a  m" src="https://user-images.githubusercontent.com/4262050/88310703-99e14880-ccd5-11ea-88e1-f6b3082569ff.png">

**Comment by bjrmatos** [comment] 2020-07-23 16:19
nevermind, i found it :) will investigate the problem, thanks!

**Comment by iamanoopmk** [comment] 2020-07-23 18:15
@bjrmatos 

I went through the jsreport code and found out that there was some styles related file that was missing from the docx that I modified.

I did the same modification on MS Word 2016 version and this issue seems to go away. But the chart colours are not applied. Colours get changed to the default blue/orange. 

Is there any specific version of MS Word that needs to be used to generate the template?

**Comment by bjrmatos** [comment] 2020-07-23 18:29
@iamanoopmk yes, the problem is the files missing, I was already preparing the code changes to don't break when the files do not exist and so far it seems that this removes the issue, or at least it produces normal docx file at the end without error

> Is there any specific version of MS Word that needs to be used to generate the template?

hard to say, i did not noticed that MS Word removes the style, color files before, i have MS Word 2019 locally

**Comment by bjrmatos** [comment] 2020-07-23 18:44
i've pushed the changes needed to don't break the execution when style, colors xml files are not present for a chart. let me know if this helps. 

if you have problems with missing colors let me know what are those, the colors i see in your docx file are the orange, blue and gray color so i'm not sure what are the custom ones you defined. maybe those were not applied when you save the document which can be a problem related to the ms word

**Comment by iamanoopmk** [comment] 2020-07-24 02:34
Thank you for the update. In the [this example](https://playground.jsreport.net/w/anon/HmjeOkfP) I have added different color to the chart but they don't take. You can take a look at it.

**Comment by bjrmatos** [comment] 2020-07-24 15:56
@iamanoopmk ok thanks for the updated example, i will take a look

**Comment by bjrmatos** [comment] 2020-08-14 02:12
i've pushed a fix for this, sorry for the long wait :)

**Closed** 2020-08-14 02:11 UTC
